language: ruby
rvm:
- 2.5.3
bundler_args: --without development
sudo: false

jdk:
- oraclejdk8

cache:
  directories:
  - tmp/solr_dl/

before_install:
- docker pull solr:7
- docker run -d -p 8983:8983 -v $PWD/lib/generators/blacklight/templates/solr/conf:/myconfig solr:7 solr-create -c blacklight-core -d /myconfig
- docker ps -a

before_script:
- bundle exec rake assets:precompile

script:
- bundle exec niftany
- bundle exec rake

env:
  global:
  - RAILS_ENV=test