language: ruby
rvm:
- 2.5.1
bundler_args: --without development
sudo: false

before_script:
- bundle exec rake db:migrate
- bundle exec rake db:seed
- bundle exec yarn
- bundle exec rails webpacker:compile

script:
- bundle exec rubocop

env:
   global:
   - RAILS_ENV=test