language: ruby
rvm:
- 2.5.1

bundler_args: --without development
sudo: false

jdk:
- oraclejdk8

cache:
  directories:
  - tmp/solr_dl/
  
script:
- bundle exec niftany
- bundle exec rake assets:precompile
- bundle exec rake

env:
- TZ=America/New_York
   global:
   - RAILS_ENV=test